# docker-compose.yml
version: '3.8'

services:
  logo-detection:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # Mount entire data directory
      - ./detections.db:/app/detections.db
    environment:
      - DB_PATH=/app/detections.db
      - MODEL_PATH=/app/data/models/best.pt
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped